name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      TAG:
        required: true
jobs:
  publish-npm-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: actions/cache@v3
        id: restore-build
        with:
          # add /packages/snap/snap.manifest.json to include an updated shasum from build due to version update in auto PR
          path: |
            ./packages/starknet-snap/dist/bundle.js
            ./packages/starknet-snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
      - name: Dry Run Publish
        run: |
          ls -al ./packages/starknet-snap/dist
          npm pack ./packages/starknet-snap --tag "$TAG" --access public
        env:
          TAG: ${{ secrets.TAG }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: 
      - publish-npm-dry-run
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v3
        id: restore-build
        with:
          # add /packages/snap/snap.manifest.json to include an updated shasum from build due to version update in auto PR
          path: |
            ./packages/starknet-snap/dist/bundle.js
            ./packages/starknet-snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
      - name: Run Publish
        run: |
          npm pack ./packages/starknet-snap --tag "$TAG" --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ secrets.TAG }}
